### PR TITLE
Fix comment string inside JSX spread element

### LINKED ISSUE #38: Wrong commentstring inside JSX spread element
The commentstring for a spread element inside of a JSX block is the default JSX `{/* */}` comment.

For example, if I have the following JSX element
```javascript
<div {...{
    id: "testo"
}}/>
```
and attempt to comment toggle the `id` attribute line using terrortylor/nvim-comment, I get
```javascript
<div {...{
    {/* id: "testo" */}
}}/>
```
which is not valid JSX.

Instead, I should get a normal JavaScript style comment.
```javascript
<div {...{
    // id: "testo"
}}/>
```

### PR DESCRIPTION
**Pull request by dwoznicki**
Fixes #38

I think this change is probably safe, even though it theoretically matches all spread elements, not just those in JSX blocks. If not, it's probably blocked until there's something like a `__parent` node selector.

### CODE REVIEW

File: lua/ts_context_commentstring/internal.lua [hunk 1]
```diff
@@ -70,6 +70,7 @@ M.config = {
     comment = { __default = '// %s', __multiline = '/* %s */' },
     call_expression = { __default = '// %s', __multiline = '/* %s */' },
     statement_block = { __default = '// %s', __multiline = '/* %s */' },
+    spread_element = { __default = '// %s', __multiline = '/* %s */' },
```
Comment (JoosepAlviste) [inline lua/ts_context_commentstring/internal.lua:73]: Could you also add this to `tsx`?

**Review by JoosepAlviste — CHANGES_REQUESTED** [review]
Looks good! Just one comment. I don't think that this should break anything.

File: lua/ts_context_commentstring/internal.lua (hunk 1 above)
Comment (dwoznicki) [reply lua/ts_context_commentstring/internal.lua:74]: Added!

**Review by JoosepAlviste — APPROVED** [review]

**Comment by JoosepAlviste** [comment]
Thanks for the improvements!
